Allow deploying rc1staging from non-master branches

diff --git a/.github/workflows/helm_deploy_dispatch.yml b/.github/workflows/helm_deploy_dispatch.yml
--- a/.github/workflows/helm_deploy_dispatch.yml
+++ b/.github/workflows/helm_deploy_dispatch.yml
@@ -48,9 +48,13 @@ jobs:
     steps:
       - id: set-config
         run: |
-          SERVICE_ACCOUNT_SUFFIX="-ro"
-          # SERVICE_ACCOUNT_SUFFIX=""
+          # SERVICE_ACCOUNT_SUFFIX="-ro"
+          SERVICE_ACCOUNT_SUFFIX=""
           [ "${{ github.ref_name }}" == master ] && SERVICE_ACCOUNT_SUFFIX=""
+          if [ "${{ github.event.inputs.action }}" == apply ] && [ "${{ github.event.inputs.deployment }}" != rc1staging ] && [ "${{ github.ref_name }}" != "master" ]; then
+            echo "ERROR: Only the master branch can be deployed to non-rc1staging environments"
+            exit 1
+          fi
           if [ "${{ github.event.inputs.deployment }}" == "cannoli" ]; then
             echo "cluster=cannoli" >> "$GITHUB_OUTPUT"
             echo "project=cannoli-380909" >> "$GITHUB_OUTPUT"
