Add merge-master-after-release job

diff --git a/.github/workflows/publish-docker-image.yml b/.github/workflows/publish-docker-image.yml
--- a/.github/workflows/publish-docker-image.yml
+++ b/.github/workflows/publish-docker-image.yml
@@ -28,19 +28,19 @@ jobs:
 
       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v2
-      
+
       - name: Log in to Docker Hub
         uses: docker/login-action@v2
         with:
           username: ${{ secrets.DOCKER_USERNAME }}
           password: ${{ secrets.DOCKER_PASSWORD }}
-      
+
       - name: Extract metadata (tags, labels) for Docker
         id: meta
         uses: docker/metadata-action@v4
         with:
           images: blockscout/blockscout
-      
+
       - name: Build & Push Docker image
         run: |
           docker buildx build \
@@ -63,3 +63,35 @@ jobs:
           --build-arg SUBNETWORK="" \
           --build-arg COIN_NAME="" \
           --push --platform=linux/arm64,linux/amd64 .
+
+  merge-master-after-release:
+    name: Merge 'master' to specific branch after release
+    runs-on: ubuntu-latest
+    env:
+      BRANCHES: production-aox-stg production-core-stg production-eth-stg production-harmony-mainnet-shard-0-stg production-lukso-stg production-optimism-goerli-stg production-optimism-stg production-rsk-stg production-sokol-stg
+    steps:
+    - uses: actions/checkout@v2
+    - name: Set Git config
+      run: |
+          git config --local user.email "actions@github.com"
+          git config --local user.name "Github Actions"
+    - name: Merge master back after release
+      run: |
+          git fetch --unshallow
+          git checkout master
+          touch errors.txt
+          for branch in $BRANCHES;
+          do
+            git fetch origin
+            echo $branch
+            git ls-remote --exit-code --heads origin $branch || { echo $branch >> errors.txt; continue; }
+            echo "Merge 'master' to $branch"
+            git checkout $branch
+            git pull || { echo $branch >> errors.txt; continue; }
+            git merge --no-ff master -m "Auto-merge master back to $branch" || { echo $branch >> errors.txt; continue; }
+            git push || { echo $branch >> errors.txt; continue; }
+            git checkout master;
+          done
+          [ -s errors.txt ] && echo "There are problems with merging 'master' to branches:" || echo "Errors file is empty"
+          cat errors.txt
+          [ ! -s errors.txt ]
